name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@main
      - name: Use Node.js 20.x
        uses: actions/setup-node@main
        with:
          node-version: 20.x
          cache: "yarn"
      - name: Install packages
        run: yarn install
      - name: Cache npm dependencies
        uses: actions/cache@main
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-
      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: webpack
          path: public/
  test:
    name: Download
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 
        uses: actions/download-artifact@main
        with:
          name: webpack
      - run: ls -lh public
